
-- drop table auth;
-- drop table users;
-- drop table groups;

create table groups (
    id integer not null primary key generated by default as identity (start with 0, increment by 10),
    name varchar(200)
);
insert into groups (id, name) values (0, 'admin');
alter table groups alter column id restart with 1000;
insert into groups(name) values
    ('users'),
    ('external');
select * from groups;

create table users (
    id integer not null primary key generated by default as identity (start with 0, increment by 1),
    group_id integer not null,
    name varchar(200),
    constraint fk_group_id foreign key (group_id) references groups(id)
);
insert into users(id, group_id, name) values (0, 0, 'admin');
select * from users;
alter table users alter column id restart with 1000;
insert into users (group_id, name) values (1001,'none');
select * from users;

create table auth (
    user_id integer not null references users(id),
    token varchar(100) not null
);
insert into auth(user_id, token) values (0, '496a3cddc8d8d4ec76343d89f1861d57199bd7b6');
select * from auth;